CREATE TABLE PROFISSIONAL(
ID_PROFIS NUMBER NOT NULL,
NOME VARCHAR2(255) NOT NULL,
CPF VARCHAR2(22) NOT NULL,
NUM_REGISTRO NUMBER NOT NULL,
TIPO_PROFIS VARCHAR2(255) NOT NULL,
SENHA VARCHAR2(100) NOT NULL,
AREA VARCHAR2(255) NOT NULL,
EMAIL VARCHAR2(100) NOT NULL ,
TELEFONE VARCHAR2(255) NOT NULL,

CONSTRAINT PK_PROFIS PRIMARY KEY(ID_PROFIS) ENABLE
);

CREATE TABLE PACIENTE(
ID_PACIENTE NUMBER NOT NULL,
NOME VARCHAR2(255) NOT NULL,
CPF VARCHAR2(22) NOT NULL,
EMAIL VARCHAR2(50) NULL,
TELEFONE VARCHAR2(50) NULL,
SEXO VARCHAR2(10) NOT NULL,
IDADE NUMBER NOT NULL,
PESO NUMBER NOT NULL,
ALTURA NUMBER NOT NULL,
RUA VARCHAR2(255) NOT NULL,
NUMERO VARCHAR2(10) NOT NULL,
BAIRRO VARCHAR2(255) NOT NULL,
CEP VARCHAR2(9) NULL,

CONSTRAINT PK_PACIENTE PRIMARY KEY(ID_PACIENTE)ENABLE
);

CREATE TABLE PROCESSO(
NOME VARCHAR2(255) NOT NULL,
DESCRICAO VARCHAR2(4000) NOT NULL,

CONSTRAINT PK_PROCESSO PRIMARY KEY(NOME) ENABLE
);

CREATE TABLE ATENDIMENTO(
ID_ATENDIMENTO NUMBER NOT NULL,
ID_PROCESSO VARCHAR2(255) NULL,
ID_PACIENTE NUMBER NULL,
ID_PROFIS NUMBER NULL,
DTA DATE NOT NULL,
CID VARCHAR2(50) NOT NULL,
AVALIACAO VARCHAR2(4000) NOT NULL,
EVOLUCAO VARCHAR2(4000) NOT NULL,
PRESCRIAO VARCHAR2(4000) NOT NULL,
OBS VARCHAR2(4000) NULL,
CONDUTA VARCHAR2(4000) NOT NULL,

CONSTRAINT PK_ANTEDIMENTO PRIMARY KEY(ID_ATENDIMENTO) ENABLE
);

ALTER TABLE ATENDIMENTO ADD CONSTRAINT PK_ID_PROCESSO FOREIGN KEY(ID_PROCESSO) REFERENCES PROCESSO(NOME);
ALTER TABLE ATENDIMENTO ADD CONSTRAINT PK_ID_PACIENTE FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE);
ALTER TABLE ATENDIMENTO ADD CONSTRAINT PK_ID_PROFISSIONAL FOREIGN KEY(ID_PROFIS) REFERENCES PROFISSIONAL(ID_PROFIS);

CREATE SEQUENCE S_PROF INCREMENT BY 1 START WITH 1 MINVALUE 1;
CREATE SEQUENCE S_PACIENTE INCREMENT BY 1 START WITH 1 MINVALUE 1;
CREATE SEQUENCE S_ATENDIMENTO INCREMENT BY 1 START WITH 1 MINVALUE 1;